language: java
addons:
  sonarcloud:
    organization: "jbarrag-github"
    token:
      secure: pHeUnnux6SnLVdFKgmCZWVy2roEmU/hJ5LKLTy+vpXkyp1WuBGZXBpBvwysxZNEljqPFZ+wIX10YOxm3TTjUVnZ2G7ei/w7bjnmm02NLf2qc2/GVfy6f1htYC5Ql3sj6KLTAGYAXNRXiqKJs2R11QAzEvnw7DdLc7lsWY5Gmg8NCkqL+8iNSy1UtskyRPCwb6v1dwxz7obU/MpnuKJYCDDk8cOyGgGOmD0DjKmhsiHi1kpK9ZnIlQrQ6MNqHgbdxeurCIqp1NvTzgPPimLfK2e6Sb6t7VW28eFp4SzMvMsQ7Tcp1+YvF4083CpZ/t83EakZ2tgvAwbzIvaIrUE6RYbnE23LpCeZZm/ZK8M7Bw3RyUK3tMtZRIjxAvr1jGIgbfkVirXZ5pkKa5VCAi3vEC6HgLSnwlZq3fxeJiJcTQN1t5H8lScXFs/f2ktl7ZItgNigXw5aQT8FU9ZXML2w1pAiTGLLlAIyVHl7RrB/P7mXGzy16wRjbnFbL4cj6KWlTnHG/1SxnLIebTwkgNavSK/dtfihIom9U5WujoHBkmk5nMNf/V9H2D/zS7OFyIG6kP4xKVJ52VYEWsPRq2Z7jCq7ath1490lA+oGKYEpAAlanQraviDs16Uy/VM9DtfXPeeOWHZlIa0MDwaFFnFLP1LSs9qJa9QoK9Sj4IWlRyKI=
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
 